# Generated by Django 4.0.2 on 2022-02-13 14:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('parentphone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('parentemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
