# Generated by Django 4.0.2 on 2022-02-14 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.URLField()),
                ('group', models.CharField(choices=[('vegetarian', 'vegetarian'), ('Fruit', 'Fruit')], max_length=100)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(max_length=100)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.kid')),
            ],
        ),
    ]
